version: '3.1'

services:
  ntripcaster_tisyang:
    restart: unless-stopped   
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERS=1#2#3#admin
        - PASS=P1#P2#P3#Soporte1113
        - MOUNT_POINTS=1#2#3#*